create table tokens
(
    id int generated by default as identity primary key ,
    token varchar not null ,
    mail varchar not null ,
    expiry_date timestamp default current_timestamp,
    used bool not null
);